insert into AUTHOR_MODEL (id, CREATE_DATE , LAST_UPDATE_DATE , NAME ) VALUES (1,CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP ,'ggqqqgg');

insert into TAG_MODEL (id, NAME ) VALUES (1,'tag_name');

insert into NEWS_MODEL (id, CONTENT, CREATE_DATE , LAST_UPDATE_DATE , TITLE , AUTHOR_ID) VALUES (1, 'content', CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP ,'title',1);

insert into NEWS_TAG (TAG_ID, NEWS_ID ) VALUES (1, 1);

insert into COMMENT_MODEL (id, CONTENT, CREATED , MODIFIED , NEWS_ID) VALUES (1, 'comment_content', CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP , 1);